#!/usr/bin/env python
"""What the paper's figures need against what outputs/benchmark holds.

    python paper/inventory.py                 # prints the table, writes paper/TODO.md
    python paper/inventory.py --out /n/netscratch/.../results   # against scratch

The plan (paper/PLAN.md) is encoded below as CLAIMS -> arms x models. For every
(model, arm) the script reports how many seeds have a report.json, whether the
cell is unrunnable by construction (merge under BatchNorm, Gaussian measure on
conv), and whether the arm exists in arms.yaml at all. TODO.md is regenerated,
never edited by hand, so it cannot drift from the disk.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))
from generate_benchmark_configs import expand_arms  # noqa: E402

BENCH = ROOT / "configs" / "benchmark"

MODELS = ["mnist_lenet", "cifar10_resnet20", "cifar10_resnet56",
          "imagenet_resnet18", "imagenet_resnet50", "imagenet_mobilenetv2", "imagenet_vit_b16",
          "wikitext_opt125m", "wikitext_opt350m", "wikitext_opt1.3b", "wikitext_opt2.7b",
          "wikitext_opt6.7b"]
FC = {"imagenet_vit_b16", "wikitext_opt125m", "wikitext_opt350m", "wikitext_opt1.3b",
      "wikitext_opt2.7b", "wikitext_opt6.7b"}
BN = {"cifar10_resnet20", "cifar10_resnet56", "imagenet_resnet18", "imagenet_resnet50",
      "imagenet_mobilenetv2"}
WANT_SEEDS = {m: 3 for m in MODELS}
WANT_SEEDS.update({"wikitext_opt2.7b": 1, "wikitext_opt6.7b": 1})

CLAIMS = {
    "C1a overlap (removal sets)": ["mash_medoid_none_delta_f", "osscar_norepair", "magnitude_mass"],
    "C1b same repair": ["mash_full_medoid_empirical_delta_f", "mash_ridge_medoid_empirical_delta_f",
                        "mash_ridge_merge_empirical_delta_f", "osscar", "random_ridge",
                        "magnitude_mass_ridge"],
    "C2 no repair": ["random", "magnitude_mass", "osscar_norepair", "mash_medoid_none_delta_f",
                     "mash_medoid_sum_delta_f", "mash_merge_sum_delta_f"],
    "C3 overall + cost": ["osscar", "mash_full_medoid_empirical_delta_f",
                          "mash_ridge_merge_empirical_delta_f", "mash_ridge_medoid_empirical_delta_f",
                          "random_ridge", "magnitude_mass_ridge"],
    "C4 measure (FC only)": ["mash_merge_sum_delta_f", "mash_gaussian_merge_sum_delta_f",
                             "mash_ridge_merge_empirical_delta_f",
                             "mash_ridge_gaussian_merge_empirical_delta_f",
                             "mash_medoid_none_delta_f", "mash_gaussian_medoid_none_delta_f"],
    "C5c certificate (benchmark cells)": ["mash_certified", "mash_merge_sum_cylinder",
                                          "mash_medoid_sum_cylinder",
                                          "mash_ridge_merge_empirical_cylinder",
                                          "mash_ridge_medoid_empirical_cylinder",
                                          "mash_full_medoid_empirical_cylinder"],
}
CLAIM_MODELS = {"C4 measure (FC only)": [m for m in MODELS if m in FC]}


BIG = {"wikitext_opt2.7b", "wikitext_opt6.7b"}
PAPER_BIG = {"random", "random_ridge", "magnitude_mass", "magnitude_mass_ridge", "osscar",
             "osscar_norepair", "mash_medoid_none_delta_f", "mash_medoid_sum_delta_f",
             "mash_merge_sum_delta_f", "mash_ridge_merge_empirical_delta_f",
             "mash_full_medoid_empirical_delta_f", "mash_merge_sum_cylinder"}


def applicable(arm: str, model: str) -> str | None:
    """None if runnable and planned; else why not."""
    if model in BIG and arm not in PAPER_BIG:
        return "not in the reduced big-OPT set"
    if "merge" in arm and model in BN:
        return "merge refused under BatchNorm"
    if "gaussian" in arm and model not in FC:
        return "Gaussian measure is FC-only"
    return None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(ROOT / "outputs" / "benchmark"),
                    help="results root with <model>__<arm>/seed_*/report.json")
    args = ap.parse_args()
    out = Path(args.out)

    known = {a["name"] for a in expand_arms(yaml.safe_load((BENCH / "arms.yaml").read_text()))}

    def seeds_done(model: str, arm: str) -> int:
        return len(list((out / f"{model}__{arm}").glob("seed_*/report.json")))

    lines = ["# TODO -- generated by paper/inventory.py; do not edit",
             "", f"Results root: `{out}`", "",
             "Legend: `3/3` seeds done / wanted, `--` unrunnable by construction, "
             "`ARM?` arm not defined in arms.yaml yet.", ""]
    missing: dict[str, list[tuple[str, str, int]]] = {}
    undefined: set[str] = set()
    for claim, arms in CLAIMS.items():
        models = CLAIM_MODELS.get(claim, MODELS)
        lines += [f"## {claim}", "", "| arm | " + " | ".join(m.replace("wikitext_", "").replace("imagenet_", "in_").replace("cifar10_", "c10_") for m in models) + " |",
                  "|---|" + "---|" * len(models)]
        for arm in arms:
            row = [arm]
            for m in models:
                why = applicable(arm, m)
                if arm not in known:
                    row.append("ARM?"); undefined.add(arm); continue
                if why:
                    row.append("--"); continue
                n, want = seeds_done(m, arm), WANT_SEEDS[m]
                row.append(f"{n}/{want}" if n < want else f"**{n}/{want}**")
                if n < want:
                    missing.setdefault(claim, []).append((m, arm, want - n))
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    lines += ["## Cells still to run (any claim), by model", ""]
    by_model: dict[str, dict[str, int]] = {}
    for claim, cells in missing.items():
        for m, arm, k in cells:
            by_model.setdefault(m, {})[arm] = max(by_model.get(m, {}).get(arm, 0), k)
    total = 0
    for m in MODELS:
        cells = by_model.get(m)
        if not cells:
            lines.append(f"- **{m}**: complete"); continue
        n_runs = sum(cells.values()); total += n_runs
        lines.append(f"- **{m}** ({len(cells)} cells, {n_runs} seed-runs): "
                     + ", ".join(f"{a} (+{k})" for a, k in sorted(cells.items())))
    lines += ["", f"**{total} seed-runs missing in total.**"]
    if undefined:
        lines += ["", "## Arms the plan names that arms.yaml does not define yet", ""]
        lines += [f"- `{a}`" for a in sorted(undefined)]
    lines += ["", "## Analysis figures (not benchmark cells)", "",
              "- C5a chain (Theorem 1, eq. 8) and C5b certificate along a pass (Cor. 1, eq. 16): "
              "port studies/score_vs_oracle/{run,ward_certificate}.py to paper/figs and run at seed 0 "
              "on lenet, resnet20, resnet56, resnet18, vit, opt125m, opt350m."]
    text = "\n".join(lines) + "\n"
    (ROOT / "paper" / "TODO.md").write_text(text)
    print(text)


if __name__ == "__main__":
    main()
